### ISSUE TITLE
Add Show Regex

### ISSUE THREAD

**Issue by yaitskov** [haskell-hvr/regex-base#14]
Hi,

Why Regex type doesn't implement Show instance.
In my case I use Regex in command line interface - optparse-applicative compiles pattern string into regex (for stricter type safty of course), but it might be useful to print optparse output later and Regex is only type I cannot print.

**Comment by phadej** [comment]
`regex-base` doesn't have any concrete implementation. Which one you are using, `regex-posix`, `regex-tdfa`, some other?
`regex-posix`'s `Regex` is to the first approximation a pointer to some opaque C struct, and [`regcomp`](https://linux.die.net/man/3/regcomp) interface doesn't seem to have any way to get any debug info out. `regex-tdfa`'s `Regex` output is less opaque, still internal compiled DFA representation might not make any sense.

I'd suggest wrapping `Regex` in something like:

```haskell
data ShowableRegex = SR String Regex

instance Show ShowableRegex where
    showsPrec d (SB s _r) = showParen (d > 10)
        $ showString "makeShowableRegex "
        . showsPrec 11 s

makeShowableRegex :: String -> ShowableRegex
makeShowableRegex s = SR s (makeRegex s)
```
