### ISSUE TITLE
Add a co-maintainer

### ISSUE THREAD

**Issue by andreasabel** [haskell-hvr/regex-base#9]
@hvr you are currently the only maintainer for the `regex`-family (except for `regex-tdfa`), see e.g. https://hackage.haskell.org/package/regex-base/maintainers/.  And you are maintaining tons of packages!

I suggest you add a co-maintainer who can attend to simple issues such as keeping these packages buildable.
I volunteer to help with these janitor issues like merging the PRs (#2, #3, #8) and making a release on hackage (a revision won't do it this time).  
Keeping things buildable is my sole motivation for these packages, I do not have any ambition to add/change things.

With GHC 9.0.1 released now, restoring the build for these packages is becoming urgent.

**Comment by sjakobi** [comment]
Thanks for this initiative @andreasabel! :)

You could try contacting @emilypi who AFAIK is trying to improve the maintenance situation in some the libraries which @hvr was working on.

**Comment by andreasabel** [comment]
I have been added as co-maintainer by Herbert.  Closing this for now (until I need help ;-D).

**Comment by andreasabel** [comment]
Er, @hvr, I also need to be added here: https://hackage.haskell.org/package/regex-base/maintainers/

**Comment by andreasabel** [comment]
Done.
